server:
  port: 9091

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/fallback

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 30000
