server:
  port: 9091
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: ["text/html","text/xml","application/xml","application/json","application/octet-stream"]

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      httpclient:
        connect-timeout: 3000
        response-timeout: PT20S
        pool:
          max-idle-time: PT1S
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      http-method-specify: true
